print('Interger Number')
print(2)
print('Float Number')
print(2.5)
print('Complex Number')
print(2+2j)
print('String')
print('Hello, World!')
print('Boolean')
print(True)
print('List)')
print(['Agua','Aire','Fuego','Tierra'])
print('Tuple')
print("('Azul','Rojo','Amarillo')")
print('Set')
print('set={0,1,2,3,4,5}')
print('Dictionary')
print('dict={a,b,c,d,e}')
print("Euclidian Distance")
print("persona=[[2,3]]")
print("objeto=[[10,8]]")
x=(((10-2)**2+(8-3)**2)**(1/2))
print("=")
print(x)